# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kanastra
      POSTGRES_PASSWORD: kanastra_challenge
      POSTGRES_DB: db_kanastra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: