version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kanastra
      POSTGRES_PASSWORD: kanastra_challenge
      POSTGRES_DB: db_kanastra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
